version: '3.8'

services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8100
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      # database connection here
    ports:
      - 8100:8100
    env_file:
      - ./.env.prod
      # database connection here
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginxbackend:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - backend

    env_file:
      - ./.env.prod.db
      # backend connection settings here
      # - BACKEND_HOSTNAME=backend
      # - BACKEND_URL=http://backend
      # - BACKEND_URL_WITH_PORT=http://backend:1234


  frontend:
    build: ./ngFrontEnd
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1338:4200
    depends_on:
      - nginxbackend

volumes:
  postgres_data:
  static_volume:
  media_volume: